# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -28explay@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
    global:
        - CODECOV_TOKEN="e79cc682-88fe-44fb-8144-b52f35d3836d"
